package onnara;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2021-12-29T15:29:37.078+09:00
 * Generated source version: 2.7.15
 * 
 */
@WebService(targetNamespace = "http://hamoni.mogaha.go.kr/bms", name = "BmsSifComService_V2Port")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BmsSifComServiceV2Port {

    @WebResult(name = "addExchangeFileInfoResponse", targetNamespace = "http://hamoni.mogaha.go.kr/bms", partName = "addExchangeFileInfoResponse")
    @WebMethod
    public BmsLnkIniCommonResVO addExchangeFileInfo(
        @WebParam(partName = "addExchangeFileInfo", name = "addExchangeFileInfo", targetNamespace = "http://hamoni.mogaha.go.kr/bms")
        BmsLnkIniComAddAttachReqVO addExchangeFileInfo
    ) throws Exception_Exception;

    @WebResult(name = "getExchangeIDResponse", targetNamespace = "http://hamoni.mogaha.go.kr/bms", partName = "getExchangeIDResponse")
    @WebMethod
    public BmsLnkIniComExchangeIdResVO getExchangeID(
        @WebParam(partName = "getExchangeID", name = "getExchangeID", targetNamespace = "http://hamoni.mogaha.go.kr/bms")
        BmsLnkIniLoginVO getExchangeID
    ) throws Exception_Exception;

    @WebResult(name = "addFileUpLoadInfoResponse", targetNamespace = "http://hamoni.mogaha.go.kr/bms", partName = "addFileUpLoadInfoResponse")
    @WebMethod
    public BmsLnkIniComAddFileUpLoadInfoResVO addFileUpLoadInfo(
        @WebParam(partName = "addFileUpLoadInfo", name = "addFileUpLoadInfo", targetNamespace = "http://hamoni.mogaha.go.kr/bms")
        BmsLnkIniComAddFileUpLoadInfoReqVO addFileUpLoadInfo
    ) throws Exception_Exception;

    @WebResult(name = "getExchangeFileResponse", targetNamespace = "http://hamoni.mogaha.go.kr/bms", partName = "getExchangeFileResponse")
    @WebMethod
    public BmsLnkIniComGetAttachResVO getExchangeFile(
        @WebParam(partName = "getExchangeFile", name = "getExchangeFile", targetNamespace = "http://hamoni.mogaha.go.kr/bms")
        BmsLnkIniComGetAttachReqVO getExchangeFile
    ) throws Exception_Exception;

    @WebResult(name = "isAliveResponse", targetNamespace = "http://hamoni.mogaha.go.kr/bms", partName = "isAliveResponse")
    @WebMethod
    public boolean isAlive();
}
