
package onnara;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.handler.Handler;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2021-12-29T15:29:37.047+09:00
 * Generated source version: 2.7.15
 * 
 */
public final class BmsSifComServiceV2Port_BmsSifComServiceV2Port_Client {

    private static final QName SERVICE_NAME = new QName("http://hamoni.mogaha.go.kr/bms", "BmsSifComService_V2");

    private BmsSifComServiceV2Port_BmsSifComServiceV2Port_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BmsSifComServiceV2.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BmsSifComServiceV2 ss = new BmsSifComServiceV2(wsdlURL, SERVICE_NAME);
        BmsSifComServiceV2Port port = ss.getBmsSifComServiceV2Port();

        List<Handler> handlerList = new ArrayList<Handler>();
        handlerList.add(new AttachFileHandler());
        ((BindingProvider) port).getBinding().setHandlerChain(handlerList);

//        {
//        System.out.println("Invoking addExchangeFileInfo...");
//        onnara.BmsLnkIniComAddAttachReqVO _addExchangeFileInfo_addExchangeFileInfo = null;
//        try {
//            onnara.BmsLnkIniCommonResVO _addExchangeFileInfo__return = port.addExchangeFileInfo(_addExchangeFileInfo_addExchangeFileInfo);
//            System.out.println("addExchangeFileInfo.result=" + _addExchangeFileInfo__return);
//
//        } catch (Exception_Exception e) {
//            System.out.println("Expected exception: Exception has occurred.");
//            System.out.println(e.toString());
//        }
//            }
//        {
//        System.out.println("Invoking getExchangeID...");
//        onnara.BmsLnkIniLoginVO _getExchangeID_getExchangeID = null;
//        try {
//            onnara.BmsLnkIniComExchangeIdResVO _getExchangeID__return = port.getExchangeID(_getExchangeID_getExchangeID);
//            System.out.println("getExchangeID.result=" + _getExchangeID__return);
//
//        } catch (Exception_Exception e) {
//            System.out.println("Expected exception: Exception has occurred.");
//            System.out.println(e.toString());
//        }
//            }
//        {
//        System.out.println("Invoking addFileUpLoadInfo...");
//        onnara.BmsLnkIniComAddFileUpLoadInfoReqVO _addFileUpLoadInfo_addFileUpLoadInfo = null;
//        try {
//            onnara.BmsLnkIniComAddFileUpLoadInfoResVO _addFileUpLoadInfo__return = port.addFileUpLoadInfo(_addFileUpLoadInfo_addFileUpLoadInfo);
//            System.out.println("addFileUpLoadInfo.result=" + _addFileUpLoadInfo__return);
//
//        } catch (Exception_Exception e) {
//            System.out.println("Expected exception: Exception has occurred.");
//            System.out.println(e.toString());
//        }
//            }
        {
        System.out.println("Invoking getExchangeFile...");
        onnara.BmsLnkIniComGetAttachReqVO _getExchangeFile_getExchangeFile = new BmsLnkIniComGetAttachReqVO();

            BmsLnkIniLoginVO bmsLnkIniLoginVO = new BmsLnkIniLoginVO();

            /* 온-나라 시스템에 등록된 시스템 코드*/
            bmsLnkIniLoginVO.setSystemId("onnara_mobile");
            /* 온-나라 시스템 인증 키 */
            bmsLnkIniLoginVO.setAuthKey("4cd3676874ce7289f6bcfdbcc8de091b399fa0d7cfc16e6ca8bdca229101bae7");
            /* 온-나라 사용자 부서코드 */
            bmsLnkIniLoginVO.setDeptCd("6410000");
            /* 온-나라 사용자 로그인 ID */
            bmsLnkIniLoginVO.setLoginId("admin");
            _getExchangeFile_getExchangeFile.setLoginVo(bmsLnkIniLoginVO);
            /* 온-나라 시스템의 첨부파일 ID */
            _getExchangeFile_getExchangeFile.setFileId("031db9a63bccb76b36f5ab52e18ffa70");
            
            port.getExchangeID(bmsLnkIniLoginVO);

        try {
            onnara.BmsLnkIniComGetAttachResVO _getExchangeFile__return = port.getExchangeFile(_getExchangeFile_getExchangeFile);
            System.out.println("getExchangeFile.result=" + _getExchangeFile__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
//        {
//        System.out.println("Invoking isAlive...");
//        boolean _isAlive__return = port.isAlive();
//        System.out.println("isAlive.result=" + _isAlive__return);
//
//
//        }

        System.exit(0);
    }

}
