package onnara;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2021-12-29T15:29:37.093+09:00
 * Generated source version: 2.7.15
 * 
 */
@WebServiceClient(name = "BmsSifComService_V2", 
                  wsdlLocation = "BmsSifComService_V2.wsdl",
                  targetNamespace = "http://hamoni.mogaha.go.kr/bms") 
public class BmsSifComServiceV2 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://hamoni.mogaha.go.kr/bms", "BmsSifComService_V2");
    public final static QName BmsSifComServiceV2Port = new QName("http://hamoni.mogaha.go.kr/bms", "BmsSifComService_V2Port");
    static {
        URL url = BmsSifComServiceV2.class.getResource("BmsSifComService_V2.wsdl");
        if (url == null) {
            url = BmsSifComServiceV2.class.getClassLoader().getResource("BmsSifComService_V2.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(BmsSifComServiceV2.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "BmsSifComService_V2.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public BmsSifComServiceV2(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BmsSifComServiceV2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BmsSifComServiceV2() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BmsSifComServiceV2(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BmsSifComServiceV2(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BmsSifComServiceV2(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BmsSifComServiceV2Port
     */
    @WebEndpoint(name = "BmsSifComService_V2Port")
    public BmsSifComServiceV2Port getBmsSifComServiceV2Port() {
        return super.getPort(BmsSifComServiceV2Port, BmsSifComServiceV2Port.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BmsSifComServiceV2Port
     */
    @WebEndpoint(name = "BmsSifComService_V2Port")
    public BmsSifComServiceV2Port getBmsSifComServiceV2Port(WebServiceFeature... features) {
        return super.getPort(BmsSifComServiceV2Port, BmsSifComServiceV2Port.class, features);
    }

}
