
package onnara;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.15
 * 2021-12-29T15:29:37.078+09:00
 * Generated source version: 2.7.15
 */

@WebFault(name = "Exception", targetNamespace = "http://hamoni.mogaha.go.kr/bms")
public class Exception_Exception extends java.lang.Exception {
    
    private onnara.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, onnara.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, onnara.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public onnara.Exception getFaultInfo() {
        return this.exception;
    }
}
